### ISSUE TITLE
"Error parsing reference" when trying to build docker

### ISSUE THREAD

**Issue by ramBrain** [dorianps/LINDA#35]
Dear developers,

when running `Build.linda.windows.bat` I encounter this error:

`dorianps/linda:3/02" is not a valid repository/tag: invalid reference format "Docker built commands ended, exiting shortly.
`
and the building crashes. What would you suggest to do?

Many thanks,
Ramtin

**Comment by dorianps** [comment]
I have created those files few years ago and have neither checked nor used
them anymore. Maybe the tag is wrong due to the slash. You can troubleshoot
yourself a bit, oranually enter the tag. You can also try to get an
existing docker container from DockerHub, no need to build your own on
Windows. I don't have time right now to fix the Windows bat file.

Dorian

**Comment by ramBrain** [comment]
Thank you Dorian, I indeed managed with pulling an existing container.

Ramtin
